apiVersion: apps/v1
kind: Deployment
metadata:
  name: finaiflow-api
  namespace: finaiflow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: finaiflow-api
  template:
    metadata:
      labels:
        app: finaiflow-api
    spec:
      containers:
      - name: api
        image: finaiflow:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: finaiflow-config
        - secretRef:
            name: finaiflow-secrets
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      initContainers:
      - name: migrate
        image: finaiflow:latest
        command: ["alembic", "upgrade", "head"]
        envFrom:
        - configMapRef:
            name: finaiflow-config
        - secretRef:
            name: finaiflow-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: finaiflow-api
  namespace: finaiflow
spec:
  selector:
    app: finaiflow-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: finaiflow-api-hpa
  namespace: finaiflow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: finaiflow-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80