apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- postgres.yaml
- redis.yaml
- api.yaml
- celery.yaml
- ingress.yaml

commonLabels:
  app: finaiflow
  version: v2.0.0

images:
- name: finaiflow
  newTag: latest